# Use an official Nginx image as the base
FRO M nginx:alpine

# Copy the 'index.html' file into the default nginx directory
CO PY app/index.html /usr/share/nginx/html/index.html

# Expose port 80 to access the web app
EXPOSE 80
